### PR TITLE
Makes QuantityValue bounds optional

### LINKED ISSUE #246: Makes QuantityValue bounds optional
upper and lower bounds of QuantityValues are becoming optional in Wikibase.
We should apply this change in order to still be compatible with new dumps.

See:
- https://phabricator.wikimedia.org/T115269
- https://lists.wikimedia.org/pipermail/wikidata-tech/2016-November/001050.html

### PR DESCRIPTION
**Pull request by Tpt**
Closes #246

### CODE REVIEW

**Comment by Tpt** [comment]
The CI failure is caused by a timeout with dump tests on OpenJDK 7. The other plateforms work well.

**Comment by elshimone** [comment]
It would be useful to merge this as newer dumps cannot be processed by v7.0.0 or current master

e.g. 

wdtk.sh --action rdf --output statements.rdf --z gz --offline  --rdftasks items,statements

...
2016-12-15 11:33:20 INFO  - Processing JSON dump file wikidatawiki-json-20161205
...
2016-12-15 11:31:43 INFO  - Fetched type information for property P1291 online: http://wikiba.se/ontology#ExternalId
Exception in thread "main" java.lang.NullPointerException
        at org.wikidata.wdtk.rdf.Vocabulary.getQuantityValueUri(Vocabulary.java:493)
        at org.wikidata.wdtk.rdf.values.QuantityValueConverter.getRdfValue(QuantityValueConverter.java:58)

If I build the tool using the changes in this pull request I do not get this error.

**Comment by elshimone** [comment]
Turns out the export fails later because some property types are returned as null by the PropertyRegister; I guess this PR allows this to happen.  I'll see if I can submit another PR to fix this issue.

**Comment by guenthermi** [comment]
Thank you and sorry for the late response.

**Pull request merged**
