### PR TITLE
Add clientLogin method to BasicApiConnection

### PR DESCRIPTION
**Pull request by Lhaaits**

### CODE REVIEW

**Review by wetneb — COMMENTED** [review]
Hey this looks really great, nice refactoring with your big `enum` (did not know one could do that!)

I haven't tested it yet - did you test it on your side, and with which Wikibase instance? I remember looking into this earlier and it felt quite complicated because this login workflow can involve 2FA verifications. It does not look like those are supported yet, are they? Do you think this would be doable? Not sure what the Java API would like for our users.

**Comment by Lhaaits** [comment]
By the way, do you know where all possible login error values can be found? I wasn't able to reproduce all possible values to complete the enum. For example LOGIN_THROTTLED or LOGIN_BLOCKED. I tried looking for a repo for the api.php, but no luck yet. And the docs are also not that extensive.

**Comment by Lhaaits** [comment]
@guenthermi I see you added the login error values originally. Do you by any change remember what you based those values on?

**Comment by wetneb** [comment]
@Lhaaits I would not block this PR for that. On my side I was waiting for this discussion about error codes to be resolved, but if that is stalled I would be very fine with merging this as is.

**Comment by robertvazan** [comment]
@Lhaaits I do not contribute to server-side code. Sorry I cannot be of more help.

**Comment by Lhaaits** [comment]
@robertvazan Fair enough. Thanks for the quick reply :)
@wetneb I would like to merge if that's ok. No luck finding the error codes unfortunately, except for the ones I could reproduce locally.

**Comment by wetneb** [comment]
@Lhaaits do you need to be released soon? That could probably be a new minor version (`0.14.0`).

**Comment by Lhaaits** [comment]
@wetneb Yeah a minor makes sense :)

**Pull request merged**
