### PR TITLE
Follow HTTP Redirects

### PR DESCRIPTION
**Pull request by monkey2000**
Fix for Issue #151 
Add a test case for redirecting.

---

BTW: I don't think that `getInputStreamForUrl` is a instance method.

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Doing this cast changes the behaviour of the code?

**Comment by monkey2000** [comment]
Yes. Using `setFollowRedirects` and I'm sure that it will handle redirects.
The test case passed.

**Comment by JeroenDeDauw** [comment]
Oh, I had not seen the `urlConnection.setFollowRedirects(true);` line. Silly me :)

> The test case passed.

Because you wrote it like that, I started wondering if you also verified it failed before and decided to find out. I can undo your changed to the production code, and the added test will still pass.

**Comment by monkey2000** [comment]
The test case is copyed from issue #151.
Seems like it can't handle redirects before.

**Pull request closed without merging**
