### PR TITLE
Makes clearer the cases where Snak.getValue returns null 

### PR DESCRIPTION
**Pull request by Tpt**
Avoids a getter that may return null

### CODE REVIEW

**Comment by wetneb** [comment]
How about converting it to use Optionals instead? I find it quite convenient to have this method in Snak, otherwise it's a bit annoying to have to do a cast.

**Comment by Tpt** [comment]
> How about converting it to use Optionals instead?

It's a good idea but it would be a breaking change. Having this method is indeed useful. I'm going to modify this pull request to remove the deprecation but keep having an override in ValueSnak that states that the method never returns null.

**Comment by wetneb** [comment]
You're right about the breaking change… it's going to be annoying… then I don't know. I guess we can deprecate but when we do so we need to provide a viable alternative at the same time. So I would be happy with deprecating this one and adding another method (such as `maybeGetValue` or something better) with Optionals.

**Comment by Tpt** [comment]
>  So I would be happy with  deprecating this one and adding another method (such as maybeGetValue or something better) with Optionals.

It sounds like a good option. We would keep the getValue method not deprecated for the ValueSnak interface that always have a value.

**Comment by Tpt** [comment]
Let's do an other pull request for the optional getter

**Pull request merged**
