### PR TITLE
Fix filter test to use nonempty sitelinks (NOT DONE YET)

### PR DESCRIPTION
**Pull request by JeroenDeDauw**

### CODE REVIEW

**Comment by mkroetzsch** [comment]
Well, this code was meant to be used ;-). Rather than removing it, the test should be fixed to filter only some site links and not all.

**Comment by JeroenDeDauw** [comment]
As a side note: this does not happen if you test first

#RageMarkusIntoTDD

**Comment by mkroetzsch** [comment]
I honestly don't know how test first should work in practice. This is not a critique -- I just cannot imagine how it would be done.

**Comment by JeroenDeDauw** [comment]
If you want we can pair program a kata in Java using TDD via https://floobits.com/ (this is easy to set up)

**Comment by wetneb** [comment]
Closing as stale.

**Pull request closed without merging**
