### PR TITLE
Minor change to enable calling apps to be aware of exceptions

### PR DESCRIPTION
**Pull request by brett-matson**
The of processDumpFile() method of DumpProcessingController was catching exceptions, so calling apps couldn't detect whether an error had occurred. This minor change modifies processDumpFile() to throw exceptions with their original error message after logging them with their original log message.

### CODE REVIEW

**Comment by brett-matson** [comment]
Eek. I'm nowhere near experienced enough to know why github's saying it failed. It passed the tests when I ran them through maven on the command line.

**Comment by wetneb** [comment]
It's not related to your PR, it's my own fault, the submission of coverage info fails because your PR was opened from a fork, which disables secrets in the workflow for security reasons. I'll get this fixed independently.

**Comment by brett-matson** [comment]
Phew! That's good to know.

**Comment by wetneb** [comment]
Closing as replaced by #526.

**Pull request closed without merging**
